import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/common/footer/footer";
import Navbar from "@/common/navbar/navbar";
import { Montserrat, Plus_Jakarta_Sans } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
  variable: "--font-jakarta",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${jakarta.variable} ${montserrat.variable}`}>
      <body className="antialiased base-white-bg font-jakarta">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
